In [1]:
from sklearn import datasets
from pybrain.datasets.classification import ClassificationDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised import BackpropTrainer

In [2]:
iris = datasets.load_iris()
x, y = iris.data, iris.target
dataset = ClassificationDataSet(4, 1, nb_classes=3)

In [3]:
for i in range (len(x)):
    dataset.addSample(x[i], y[i])

train_data_temp, part_data_temp = dataset.splitWithProportion(0.6)
test_data_temp, val_data_temp = part_data_temp.splitWithProportion(0.5)

In [5]:
train_data = ClassificationDataSet(4, 1, nb_classes=3)
for n in range(train_data_temp.getLength()):
    train_data.addSample(train_data_temp.getSample(n)[0], train_data_temp.getSample(n)[1])
    
test_data = ClassificationDataSet(4, 1, nb_classes=3)
for n in range(test_data_temp.getLength()):
    test_data.addSample(test_data_temp.getSample(n)[0], test_data_temp.getSample(n)[1])
    
val_data = ClassificationDataSet(4, 1, nb_classes=3)
for n in range(val_data_temp.getLength()):
    val_data.addSample(val_data_temp.getSample(n)[0], val_data_temp.getSample(n)[1])

In [6]:
print('Antes do _convertToOneOfMany')
print(train_data['target'][:5])

train_data._convertToOneOfMany()
test_data._convertToOneOfMany()
val_data._convertToOneOfMany()

print('Depois do _convertToOneOfMany')
print(train_data['target'][:5])

Antes do _convertToOneOfMany
[[0]
 [0]
 [2]
 [2]
 [0]]
Depois do _convertToOneOfMany
[[1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]]


In [10]:
from pybrain.structure.modules import SoftmaxLayer

net = buildNetwork(4, 5, 3, outclass=SoftmaxLayer)
trainer = BackpropTrainer(net, dataset=train_data, learningrate=0.01, momentum=0.9)
trainer.trainOnDataset(train_data, 100)

from pybrain.utilities import percentError

out = net.activateOnDataset(test_data).argmax(axis=1)
print('Erro de teste: %f ' % percentError(out, test_data['class']))

Erro de teste: 0.000000 


In [11]:
import numpy as np

out = net.activateOnDataset(val_data).argmax(axis=1)
print('Erro de validação: %f' % percentError(out, val_data['class']))

Erro de validação: 3.333333


In [12]:
print('Validação')
print('Saída da rede: \t', out)
print('Correto:\t', val_data['class'][:,0])

Validação
Saída da rede: 	 [2 1 2 2 2 0 1 2 0 0 2 0 2 1 0 1 1 0 1 2 0 1 1 1 1 2 0 1 0 2]
Correto:	 [2 1 2 2 2 0 1 2 0 0 2 0 2 1 0 1 1 0 1 2 0 1 1 1 1 2 0 1 0 1]
