In [1]:
import numpy as np

In [2]:
# append
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
np.append(a, [4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
np.append(a,[[5,6]])

array([1, 2, 3, 4, 5, 6])

In [6]:
np.append(a,[[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.append(a,[[5,6,7]], axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [8]:
np.append(a,[5,6,7], axis=0)

ValueError: all the input arrays must have same number of dimensions

In [9]:
a.ndim

2

In [10]:
a2 = np.array([5,6,7])
a2.ndim

1