In [6]:
import numpy as np

In [10]:
val1, val2, val3 = np.loadtxt('dados.txt', skiprows=1, unpack=True)
print(val1)
print(val2)
print(val3)

[ 0.1212  0.104   0.5661  0.762 ]
[ 0.842     0.5422    0.932     0.847361]
[ 0.3672   0.34551  0.2344   0.1538 ]


In [13]:
my_array = np.genfromtxt('dados2.txt', skip_header=1, filling_values=-999)
print(my_array)

[[  1.21200000e-01   8.42000000e-01   3.67200000e-01]
 [ -9.99000000e+02   5.42200000e-01   3.45510000e-01]
 [  5.66100000e-01   9.32000000e-01  -9.99000000e+02]
 [  7.62000000e-01   8.47361000e-01   1.53800000e-01]]
