In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array_split(a,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [5]:
np.array_split(a,2,axis=1)

[array([[1, 2],
        [4, 5]]), array([[3],
        [6]])]

In [6]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
arrays = np.array_split(b,2,axis=0)
for array in arrays:
    print(array)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [8]:
print(arrays)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
