In [9]:
import numpy as np

In [10]:
arr = np.array([1,2,3])

In [11]:
arr

array([1, 2, 3])

In [12]:
np.insert(arr, 1, 10)

array([ 1, 10,  2,  3])

In [13]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]]
2


In [16]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[4 6]
[3 7]


In [17]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [18]:
np.insert(a, 0, 5, axis=0)

array([[5, 5],
       [1, 2],
       [3, 4]])