In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
b

array([[5, 6]])

In [5]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
b.T

array([[5],
       [6]])

In [9]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])