In [2]:
import numpy

In [3]:
a = numpy.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [4]:
type(a)

numpy.ndarray

In [6]:
mat = numpy.array([[1, 2], [3, 4]])
mat

array([[1, 2],
       [3, 4]])

In [8]:
print(mat[1][1])
print(mat[-1][-1])

4
4


In [9]:
mat[1,:]

array([3, 4])

In [10]:
mat[:,0]

array([1, 3])

In [11]:
mat.transpose()

array([[1, 3],
       [2, 4]])

In [12]:
m1 = numpy.array([[1, 2], [3, 4]])
m2 = numpy.array([[5, 6], [7, 8]])
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [13]:
m1 - m2

array([[-4, -4],
       [-4, -4]])

In [14]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [15]:
m3 = numpy.array([1,2,3,4])
m3.sum()

10

In [16]:
m3.argmax()

3

In [17]:
m3.argmin()

0