In [1]:
import numpy as np

In [2]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])

In [3]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [5]:
m2 / m1

array([[ 7. ,  4. ,  3. ],
       [ 2.5,  2.2,  2. ]])

In [6]:
np.matrix.round(m2 / m1)

array([[ 7.,  4.,  3.],
       [ 2.,  2.,  2.]])

In [7]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
10 * m2

array([[ 70,  80,  90],
       [100, 110, 120]])

In [9]:
 m1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
m1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [12]:
m2 - 1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
m1 * m2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [14]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
m1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])