In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [4]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [5]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [6]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [7]:
np.repeat(3,4)

array([3, 3, 3, 3])