In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
np.tile(a, 2)

array([1, 2, 3, 1, 2, 3])

In [4]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [5]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
np.tile(b,2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])