In [3]:
l = [20, 30, 10, 40]
print(l[1:3])
print(l[::2])

[30, 10]
[20, 10]


In [5]:
import numpy as np

a = np.array(l)
a

array([20, 30, 10, 40])

In [8]:
print(a[1:3])
print(a[::2])

[30 10]
[20 10]


In [9]:
l

[20, 30, 10, 40]

In [11]:
l2 = l[:]
l2

[20, 30, 10, 40]

In [12]:
l2[0] = 1000
print(l)
print(l2)

[20, 30, 10, 40]
[1000, 30, 10, 40]


In [13]:
a

array([20, 30, 10, 40])

In [14]:
b = a[:]
b

array([20, 30, 10, 40])

In [15]:
b[0] = 1000
print(a)
print(b)

[1000   30   10   40]
[1000   30   10   40]


In [16]:
b[:] = 42
a

array([42, 42, 42, 42])

In [17]:
c = a.copy()
print(c)
print(a)

[42 42 42 42]
[42 42 42 42]


In [18]:
c[0] = 1000000
print(c)
print(a)

[1000000      42      42      42]
[42 42 42 42]
